# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Sam Loyd
# Description of the Site
description: Data Science Project Portfolio
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/SDLoyd/SDLoyd.github.io/master/assets/images/cover.jpg
# heroimage: https://unsplash.com/photos/Q1p7bh3SHj8


# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sdloyd@my365.bellevue.edu
facebook_username: 
twitter_username: sdloyd@my365.bellevue.edu
instagram_username: 
linkedin_username: 
github_username: SDLoyd
youtube_channel_id: UCJP33t2ZiB-OSMbX1En-_tg
reddit_username: 
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Sam

# Name of the Author
author-name: Sam Loyd
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/SDLoyd/SDLoyd.github.io/master/assets/images/face.png
# 60 Words About the Author
author-about: Aspiring Data Scientist with over 25 years of IT related experience as a developer, a system adminstrator, a database andministrator and most recently as a manager.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/SDLoyd

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
