# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Sam Loyd
# Description of the Site
description: Data Science Portfolio
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://raw.githubusercontent.com/SDLoyd/SDLoyd.github.io/master/assets/images/cover.jpg
# heroimage: https://unsplash.com/photos/Q1p7bh3SHj8


# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: sdloyd@my365.bellevue.edu
facebook_username: 
twitter_username: SDLoydDS
instagram_username: 
linkedin_username: s-d-loyd-495866216
github_username: SDLoyd
youtube_channel_id: UCJP33t2ZiB-OSMbX1En-_tg
reddit_username: 
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: Sam

# Name of the Author
author-name: Sam Loyd
# URL for the Image of the Author
author-image: https://raw.githubusercontent.com/SDLoyd/SDLoyd.github.io/master/assets/images/face.png
# 60 Words About the Author
author-about: <font size="+2"><b>Sam Loyd</font></b><br><br><b>Background</b><br><br><li>Data scientist with over 28 years of IT related experience as a developer, a system administrator, a database administrator and most recently as an IT manager.<br><br><b>Education</b><br><br><li>During my undergraduate studies, I dual majored in math and computer science. In the next few weeks, I will complete my masters degree in data science.<br><br><b>Interests</b><br><br><li>My hobbies include gardening, reading, and I recenty started my journey as an apprentice falconer.<br><br><b><font size="+1">I have worked with data my entire career ... It is what I do!</font></b><br>
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/SDLoyd

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
